DEMO_PRODUCTS = [
    {
        "sku": "KONG-001",
        "asin": "B0002AR0I8",
        "title": "KONG Classic Dog Toy",
        "brand": "KONG",
        "product_type": "Dog Toys",
        "price": 18.99,
        "bullet_1": "Made from KONG Classic red rubber formula",
        "bullet_2": "",
        "bullet_3": "",
        "bullet_4": "",
        "bullet_5": "",
        "description": "",
        "material": "Natural rubber",
        "colour": "Red",
        "size": "Medium",
        "weight": "",
        "breed_size": "",
        "age_range": "",
        "is_dishwasher_safe": "",
        "chew_strength": "",
        "item_shape": "",
        "special_feature": "",
        "included_components": "",
        "sport": "",
        "target_species": "Dog",
        "care_instructions": "",
        "country_of_origin": "",
    },
    {
        "sku": "KONG-002",
        "asin": "B0002DHV16",
        "title": "KONG Puppy Toy",
        "brand": "KONG",
        "product_type": "Dog Toys",
        "price": 12.99,
        "bullet_1": "Designed for puppy teeth and gums",
        "bullet_2": "",
        "bullet_3": "",
        "bullet_4": "",
        "bullet_5": "",
        "description": "",
        "material": "",
        "colour": "Pink/Blue",
        "size": "Small",
        "weight": "",
        "breed_size": "",
        "age_range": "",
        "is_dishwasher_safe": "",
        "chew_strength": "",
        "item_shape": "",
        "special_feature": "",
        "included_components": "",
        "sport": "",
        "target_species": "Dog",
        "care_instructions": "",
        "country_of_origin": "",
    },
    {
        "sku": "KONG-003",
        "asin": "B00280MUVC",
        "title": "KONG Extreme Dog Toy",
        "brand": "KONG",
        "product_type": "Dog Toys",
        "price": 21.99,
        "bullet_1": "",
        "bullet_2": "",
        "bullet_3": "",
        "bullet_4": "",
        "bullet_5": "",
        "description": "",
        "material": "",
        "colour": "Black",
        "size": "Large",
        "weight": "",
        "breed_size": "",
        "age_range": "",
        "is_dishwasher_safe": "",
        "chew_strength": "",
        "item_shape": "",
        "special_feature": "",
        "included_components": "",
        "sport": "",
        "target_species": "",
        "care_instructions": "",
        "country_of_origin": "",
    },
    {
        "sku": "KONG-004",
        "asin": "B003ALMW0M",
        "title": "KONG Cozie Marvin Moose",
        "brand": "KONG",
        "product_type": "Dog Toys",
        "price": 8.99,
        "bullet_1": "Soft and cuddly plush dog toy",
        "bullet_2": "Extra layer of material for added strength",
        "bullet_3": "",
        "bullet_4": "",
        "bullet_5": "",
        "description": "",
        "material": "",
        "colour": "Brown",
        "size": "Medium",
        "weight": "",
        "breed_size": "",
        "age_range": "",
        "is_dishwasher_safe": "",
        "chew_strength": "",
        "item_shape": "",
        "special_feature": "",
        "included_components": "",
        "sport": "",
        "target_species": "Dog",
        "care_instructions": "",
        "country_of_origin": "",
    },
    {
        "sku": "KONG-005",
        "asin": "B001ARQIGQ",
        "title": "KONG Wobbler Treat Dispensing Toy",
        "brand": "KONG",
        "product_type": "Dog Toys",
        "price": 24.99,
        "bullet_1": "",
        "bullet_2": "",
        "bullet_3": "",
        "bullet_4": "",
        "bullet_5": "",
        "description": "",
        "material": "",
        "colour": "Red",
        "size": "Large",
        "weight": "",
        "breed_size": "",
        "age_range": "",
        "is_dishwasher_safe": "",
        "chew_strength": "",
        "item_shape": "",
        "special_feature": "",
        "included_components": "",
        "sport": "",
        "target_species": "",
        "care_instructions": "",
        "country_of_origin": "",
    },
]
