"""
Demo data — 16 KONG products across multiple categories.
Includes pre-computed research summaries with confidence scores.
~25% attribute completeness to demonstrate PILO's enrichment value.
"""

DEMO_PRODUCTS = [
    {
        "sku": "KONG-001", "asin": "B0002AR0I8", "ean_gtin": "0035585111018",
        "title": "KONG Classic Dog Toy", "brand": "KONG",
        "product_type": "Dog Toys", "price": 18.99,
        "bullet_1": "Made from KONG Classic red rubber formula",
        "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "Natural rubber", "colour": "Red", "size": "Medium",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-002", "asin": "B0002DHV16", "ean_gtin": "0035585012100",
        "title": "KONG Puppy Toy", "brand": "KONG",
        "product_type": "Dog Toys", "price": 12.99,
        "bullet_1": "Designed for puppy teeth and gums",
        "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Pink/Blue", "size": "Small",
        "weight": "", "breed_size": "Small Breeds", "age_range": "Puppy",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-003", "asin": "B00280MUVC", "ean_gtin": "0035585121048",
        "title": "KONG Extreme Dog Toy", "brand": "KONG",
        "product_type": "Dog Toys", "price": 21.99,
        "bullet_1": "", "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Black", "size": "Large",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-004", "asin": "B003ALMW0M", "ean_gtin": "0035585159164",
        "title": "KONG Cozie Marvin Moose", "brand": "KONG",
        "product_type": "Dog Toys", "price": 8.99,
        "bullet_1": "Soft and cuddly plush dog toy",
        "bullet_2": "Extra layer of material for added strength",
        "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Brown", "size": "Medium",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-005", "asin": "B001ARQIGQ", "ean_gtin": "0035585131214",
        "title": "KONG Wobbler Treat Dispensing Toy", "brand": "KONG",
        "product_type": "Dog Toys", "price": 24.99,
        "bullet_1": "", "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Red", "size": "Large",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-006", "asin": "B0002DJONY", "ean_gtin": "0035585775050",
        "title": "KONG Goodie Bone", "brand": "KONG",
        "product_type": "Dog Toys", "price": 14.49,
        "bullet_1": "Stuff with treats for extended play",
        "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "Natural rubber", "colour": "Red", "size": "Medium",
        "weight": "", "breed_size": "", "age_range": "Adult",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "Bone",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-007", "asin": "B00BCS8CLA", "ean_gtin": "0035585034240",
        "title": "KONG Squeezz Ball", "brand": "KONG",
        "product_type": "Dog Toys", "price": 10.99,
        "bullet_1": "", "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Assorted", "size": "Medium",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "Ball",
        "special_feature": "", "included_components": "", "sport": "Fetch",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-008", "asin": "B001ARQIHE", "ean_gtin": "0035585036014",
        "title": "KONG Flyer", "brand": "KONG",
        "product_type": "Dog Toys", "price": 15.49,
        "bullet_1": "Soft rubber disc for gentle catching",
        "bullet_2": "Ideal for fetch and outdoor play",
        "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "Natural rubber", "colour": "Red", "size": "Large",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "Disc",
        "special_feature": "", "included_components": "", "sport": "Fetch",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-009", "asin": "B000GFRJL0", "ean_gtin": "0035585450049",
        "title": "KONG Dental Stick", "brand": "KONG",
        "product_type": "Dog Dental Care", "price": 13.99,
        "bullet_1": "", "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Red", "size": "Medium",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "Stick",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-010", "asin": "B004HHV1MG", "ean_gtin": "0035585780139",
        "title": "KONG Marathon Bone Treat", "brand": "KONG",
        "product_type": "Dog Treats", "price": 7.99,
        "bullet_1": "Long-lasting chew treat",
        "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "", "size": "Medium",
        "weight": "2 Pack", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "", "included_components": "2 Treat Refills", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-011", "asin": "B002KJ95ZA", "ean_gtin": "0035585453040",
        "title": "KONG Wubba", "brand": "KONG",
        "product_type": "Dog Toys", "price": 11.49,
        "bullet_1": "", "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "Nylon/Rubber", "colour": "Assorted", "size": "Large",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "Squeaker inside", "included_components": "", "sport": "Tug/Fetch",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-012", "asin": "B0051GN1OE", "ean_gtin": "0035585032030",
        "title": "KONG AirDog Squeakair Ball", "brand": "KONG",
        "product_type": "Dog Toys", "price": 6.99,
        "bullet_1": "Combines tennis ball and squeaker",
        "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Yellow", "size": "Medium",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "Ball",
        "special_feature": "", "included_components": "3 Pack", "sport": "Fetch",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-013", "asin": "B0080DOJ3W", "ean_gtin": "0035585450025",
        "title": "KONG Stuff-A-Ball", "brand": "KONG",
        "product_type": "Dog Toys", "price": 16.49,
        "bullet_1": "", "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "Natural rubber", "colour": "Red", "size": "Medium",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "Yes", "chew_strength": "", "item_shape": "Ball",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-014", "asin": "B007C9DCFI", "ean_gtin": "0035585033150",
        "title": "KONG Jumbler Ball", "brand": "KONG",
        "product_type": "Dog Toys", "price": 17.99,
        "bullet_1": "Two-in-one ball with interior tennis ball",
        "bullet_2": "Handles for easy pickup and tug games",
        "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Assorted", "size": "Medium/Large",
        "weight": "", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "Ball",
        "special_feature": "Squeaker inside", "included_components": "", "sport": "Fetch/Tug",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-015", "asin": "B001G0LSIU", "ean_gtin": "0035585800127",
        "title": "KONG Easy Treat Paste", "brand": "KONG",
        "product_type": "Dog Treats", "price": 9.49,
        "bullet_1": "Fill KONG toys for enrichment play",
        "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "", "size": "8 oz",
        "weight": "226g", "breed_size": "", "age_range": "",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
    {
        "sku": "KONG-016", "asin": "B0009YD64U", "ean_gtin": "0035585012056",
        "title": "KONG Senior Dog Toy", "brand": "KONG",
        "product_type": "Dog Toys", "price": 16.99,
        "bullet_1": "", "bullet_2": "", "bullet_3": "", "bullet_4": "", "bullet_5": "",
        "description": "",
        "material": "", "colour": "Purple", "size": "Large",
        "weight": "", "breed_size": "", "age_range": "Senior",
        "is_dishwasher_safe": "", "chew_strength": "", "item_shape": "",
        "special_feature": "", "included_components": "", "sport": "",
        "target_species": "Dog", "care_instructions": "", "country_of_origin": "",
    },
]


# Pre-computed AI research summaries with confidence scores
DEMO_RESEARCH = {
    "KONG-001": {
        "confidence": 0.92,
        "summary": "The KONG Classic is the gold standard in dog toys, made in the USA from proprietary natural red rubber. Features an unpredictable bounce for interactive play and a hollow centre that can be stuffed with treats. Recommended by veterinarians and trainers worldwide. Available in multiple sizes (XS to XXL). Dishwasher safe.",
        "key_features": ["Unpredictable bounce", "Stuffable hollow centre", "Vet recommended", "Dishwasher safe", "Made in USA"],
        "materials": "KONG Classic natural red rubber compound",
        "target_audience": "Dog owners seeking durable, enrichment toys for moderate to strong chewers",
        "differentiators": ["Original since 1976", "Proprietary rubber formula", "Vet-endorsed"],
    },
    "KONG-002": {
        "confidence": 0.88,
        "summary": "KONG Puppy is made from a softer, customised rubber formula designed for growing puppy teeth and gums. Available in pink or blue. Helps teach appropriate chewing behaviour.",
        "key_features": ["Softer puppy-specific rubber", "Customised formula for baby teeth", "Stuffable", "Available in pink or blue"],
        "materials": "Softer natural rubber (puppy formula)",
        "target_audience": "Puppy owners (up to 9 months)",
        "differentiators": ["Age-specific rubber hardness", "Teething relief"],
    },
    "KONG-003": {
        "confidence": 0.90,
        "summary": "KONG Extreme uses the strongest rubber formula in the KONG line, designed for power chewers. Black ultra-durable rubber withstands aggressive chewing. Same stuffable design as Classic.",
        "key_features": ["Ultra-strong black rubber", "Power chewer rated", "Stuffable", "Made in USA"],
        "materials": "KONG Extreme black ultra-durable rubber compound",
        "target_audience": "Owners of aggressive/power chewers (large breeds, determined chewers)",
        "differentiators": ["Strongest KONG rubber formula", "Power chewer approved"],
    },
    "KONG-004": {
        "confidence": 0.85,
        "summary": "KONG Cozie plush toys feature an extra layer of material for added strength. Minimal stuffing for less mess. Indoor cuddle/play toy, not designed for aggressive chewing.",
        "key_features": ["Extra reinforced fabric", "Minimal stuffing", "Indoor play", "Squeaker inside"],
        "materials": "Reinforced plush fabric with minimal polyester fill",
        "target_audience": "Dog owners wanting a soft comfort/cuddle toy",
        "differentiators": ["Reinforced construction vs standard plush", "Multiple character designs"],
    },
    "KONG-005": {
        "confidence": 0.87,
        "summary": "The KONG Wobbler is a treat-dispensing toy that wobbles, spins, and rolls as dogs push it around. Action-packed food-dispensing toy that provides mental stimulation. Unscrews for easy filling and cleaning.",
        "key_features": ["Treat dispensing", "Wobble action", "Unscrews for easy filling", "Mental stimulation", "BPA-free"],
        "materials": "FDA-compliant food-grade polymer",
        "target_audience": "Dog owners seeking mental enrichment/slow feeding solutions",
        "differentiators": ["Unique wobble motion", "Food-grade polymer", "Easy clean design"],
    },
    "KONG-006": {
        "confidence": 0.83,
        "summary": "KONG Goodie Bone is a bone-shaped classic rubber toy with two stuffable ends. Great for stuffing with KONG Easy Treat or kibble for extended play time.",
        "key_features": ["Two stuffable ends", "Classic rubber durability", "Bone shape"],
        "materials": "KONG Classic natural red rubber",
        "target_audience": "Dog owners wanting a stuffable chew toy",
        "differentiators": ["Dual-end stuffing capacity", "Bone shape for natural chewing posture"],
    },
    "KONG-007": {
        "confidence": 0.78,
        "summary": "KONG Squeezz Ball features a recessed squeaker that won't stop working even if punctured. Textured surface for easy pickup. Bouncy and durable for fetch.",
        "key_features": ["Recessed squeaker", "Won't stop squeaking", "Textured for grip", "Bouncy"],
        "materials": "Durable TPR (thermoplastic rubber)",
        "target_audience": "Active dogs who love fetch and squeaky toys",
        "differentiators": ["Patented recessed squeaker technology"],
    },
    "KONG-008": {
        "confidence": 0.86,
        "summary": "The KONG Flyer is made from flexible, soft KONG Classic rubber — gentle on teeth and gums during catching. Designed for healthy interactive outdoor play.",
        "key_features": ["Soft rubber disc", "Gentle on teeth", "Long-distance flight", "Flexible"],
        "materials": "KONG Classic natural rubber",
        "target_audience": "Active dog owners who enjoy outdoor fetch/disc games",
        "differentiators": ["Softer than hard plastic frisbees", "KONG rubber durability"],
    },
    "KONG-009": {
        "confidence": 0.75,
        "summary": "KONG Dental Stick features unique Denta-Ridges that clean teeth as dogs chew. Hollow centre for stuffing with treats or toothpaste. Promotes dental hygiene during play.",
        "key_features": ["Denta-Ridges for cleaning", "Stuffable for treats", "Dental hygiene", "Classic rubber"],
        "materials": "KONG Classic natural rubber with textured ridges",
        "target_audience": "Dog owners concerned about dental health",
        "differentiators": ["Dental cleaning ridges", "Combines play with oral care"],
    },
    "KONG-010": {
        "confidence": 0.72,
        "summary": "KONG Marathon is a long-lasting chew treat designed to fit KONG rubber toys. Provides extended chewing satisfaction. Available in chicken and liver flavours.",
        "key_features": ["Long-lasting chew", "Fits KONG toys", "Available flavours"],
        "materials": "Natural ingredients, no artificial colours",
        "target_audience": "Dog owners seeking long-lasting treat refills for KONG toys",
        "differentiators": ["Designed to fit KONG toy slots", "Extended chew duration"],
    },
    "KONG-011": {
        "confidence": 0.80,
        "summary": "KONG Wubba combines a durable ball covered in reinforced nylon fabric with long tails for shaking and tug games. Squeaker inside for added interest.",
        "key_features": ["Reinforced nylon fabric", "Squeaker ball inside", "Floppy tails for tug", "Durable construction"],
        "materials": "Ballistic nylon over rubber ball",
        "target_audience": "Dogs who love tug and fetch games",
        "differentiators": ["Unique tail design for tug", "Multi-play toy (tug, fetch, shake)"],
    },
    "KONG-012": {
        "confidence": 0.84,
        "summary": "KONG AirDog Squeakair combines a tennis ball with a squeaker. Non-abrasive felt won't damage teeth unlike standard tennis balls. Available in multiple sizes and packs.",
        "key_features": ["Non-abrasive felt", "Built-in squeaker", "Tennis ball shape", "Multi-pack"],
        "materials": "Non-abrasive felt covering over rubber ball",
        "target_audience": "Dog owners who want a safer tennis ball alternative",
        "differentiators": ["Non-abrasive felt (safer than regular tennis balls)", "Integrated squeaker"],
    },
    "KONG-013": {
        "confidence": 0.76,
        "summary": "KONG Stuff-A-Ball features a treat-stuffing groove design with Denta-Ridges for dental cleaning. Combine chewing fun with treat reward and dental hygiene.",
        "key_features": ["Treat stuffing grooves", "Denta-Ridges", "Classic rubber", "Dishwasher safe"],
        "materials": "KONG Classic natural rubber",
        "target_audience": "Dog owners wanting combined treat/dental toy",
        "differentiators": ["Groove design holds treats differently than hollow KONG", "Dental cleaning built in"],
    },
    "KONG-014": {
        "confidence": 0.79,
        "summary": "KONG Jumbler features an interior tennis ball with handles on the outside. Two-in-one design with squeakers for interactive indoor/outdoor play.",
        "key_features": ["Interior tennis ball", "Exterior handles", "Dual squeakers", "Interactive play"],
        "materials": "Durable TPR with fabric handles",
        "target_audience": "Active dogs who enjoy interactive play with owners",
        "differentiators": ["Unique ball-in-ball design", "Handles for easy tug and pickup"],
    },
    "KONG-015": {
        "confidence": 0.82,
        "summary": "KONG Easy Treat is a creamy paste designed to fill KONG toys. Simply squeeze directly into any KONG toy for instant enrichment. Multiple flavours available.",
        "key_features": ["Easy squeeze application", "Designed for KONG toys", "Can be frozen", "Multiple flavours"],
        "materials": "Food-grade ingredients, no artificial preservatives",
        "target_audience": "KONG toy owners seeking convenient treat filling",
        "differentiators": ["Purpose-built for KONG toys", "Freeze for extended play"],
    },
    "KONG-016": {
        "confidence": 0.81,
        "summary": "KONG Senior is made from a gentler rubber formula specifically designed for aging dogs with less powerful jaws and sensitive teeth/gums.",
        "key_features": ["Gentle senior rubber formula", "Stuffable", "Softer than Classic", "Made in USA"],
        "materials": "KONG Senior gentle rubber compound (purple)",
        "target_audience": "Senior dog owners (7+ years)",
        "differentiators": ["Age-specific formula softer than Classic", "Designed for aging teeth/gums"],
    },
}
